/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20VotesSol from "./ERC20Votes.sol";
export * as tokenizedBallotSol from "./TokenizedBallot.sol";
export { CallOracle__factory } from "./CallOracle__factory";
export { Lottery__factory } from "./Lottery__factory";
export { LotteryToken__factory } from "./LotteryToken__factory";
