/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyVotingToken } from "./IMyVotingToken";
export type { MyERC20Token } from "./MyERC20Token";
export type { TokenizedBallot } from "./TokenizedBallot";
